apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miner
  template:
    metadata:
      labels:
        app: miner
    spec:
      containers:
      - name: miner
        image: 746789164325.dkr.ecr.us-east-1.amazonaws.com/demoorg/miner:kubernetes
        ports:
        - name: rpc-port
          containerPort: 38332
        - name: bind-port
          containerPort: 38333

---

apiVersion: v1
kind: Service
metadata:
  name: miner-svc
spec:
  # type: NodePort
  ports:
  - name: rpc-port
    port: 38332
    protocol: TCP
  - name: bind-port
    port: 38333
    protocol: TCP
    
  selector:
    app: miner  # Ensure this matches the labels in the Deployment


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miner-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #       - "nginx.sandabgc.com.np"
      # secretName: https
  rules:
    - host: memerrpc.sandabgc.com.np
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: miner-svc
                port:
                  name: rpc-port
    - host: memerbind.sandabgc.com.np
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: miner-svc
                port:
                  name: bind-port
